# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost-system-dev
            - libboost-python-dev
            - libboost-filesystem-dev
            - freeglut3-dev
            - libxmu-dev
            - libxi-dev
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-system-dev
            - libboost-python-dev
            - libboost-filesystem-dev
            - freeglut3-dev
            - libxmu-dev
            - libxi-dev
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libboost-system-dev
            - libboost-python-dev
            - libboost-filesystem-dev
            - freeglut3-dev
            - libxmu-dev
            - libxi-dev
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libboost-system-dev
            - libboost-python-dev
            - libboost-filesystem-dev
            - freeglut3-dev
            - libxmu-dev
            - libxi-dev
      env: COMPILER=clang++-3.7
  
# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DOSG_ENABLE_C++11=ON -DOSGBUILD_OSGContribCgFX=OFF .. && make
